### ISSUE TITLE
Papasito

### ISSUE THREAD

**Issue by Gatitodelosbuenos** [AGraber/samp-dl-compat#13]
No se que decir pero,shupame la pishula

**Comment by Gatitodelosbuenos** [comment]
papasitoooooooooo

**Comment by Gatitodelosbuenos** [comment]
Que rikoooooooooooooo

**Comment by Gatitodelosbuenos** [comment]
wwuwuwuwu

**Comment by fatkok42069** [comment]
what is this
please fix bug graber please it dosent work

**Comment by Gatitodelosbuenos** [comment]
fatkok sorry man xd

**Comment by fatkok42069** [comment]
why?
please fix this graber i wan to us it but i catn
