### ISSUE TITLE
Actors dont' appear as dead in 0.3.7

### ISSUE THREAD

**Issue by Romz24** [AGraber/samp-dl-compat#17]
Why do dead actors appear as alive? Those who play from version 0.3.7 see everything is fine, and those who play with 0.3.DL see this error.
**Code:**
``CreateDynamicActor(skinid, x, y, z, angle, 0, 0.0);``

![image](https://user-images.githubusercontent.com/2458113/42381577-2ef75372-813a-11e8-9f9d-0468c8e1b827.png)
![image](https://user-images.githubusercontent.com/2458113/42381569-27dbdf86-813a-11e8-830a-cccd17ac6e03.png)

**Comment by AGraber** [comment]
Sorry for the delay, I guess you're creating them at the moment already dead right? I'll take a look into this
