### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by Chaprnks** [AGraber/samp-dl-compat#5]
I'm running a 0.3.7-R2 server, & I tried connecting via 0.3.DL client. Unfortunately this is what I got as a response:

![bbpxotw](https://user-images.githubusercontent.com/6340970/36357336-85360d00-14ca-11e8-97fb-f4dc9f1dfd83.png)

**Comment by AGraber** [comment]
Sorry, I haven't got the time to check. I've revamped the script by now, could you please check it?
Thanks

**Comment by Chaprnks** [comment]
![cridypd](https://user-images.githubusercontent.com/6340970/39392640-8e281834-4a87-11e8-834c-b92ff1959e8e.png)
