### ISSUE TITLE
permission to make my fork public

### ISSUE THREAD

**Issue by RodrigoDornelles** [AGraber/samp-dl-compat#6]
I can divulge it in forums and groups, my fork for 03DL server? (inverse of 037)
https://github.com/RodrigoDornelles/is03dl-razor-fork

**Comment by AGraber** [comment]
I checked it, but it's inconsistent and contains some errors. I will publish one soon in this same account, that's for sure.

**Comment by AGraber** [comment]
[Here it is!](https://github.com/AGraber/samp-037-compat/)
